spring:
  application:
    name: task-service

server:
  port: 8082
  contextPath: /task-service


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8302/eureka/
  instance:
    hostname: localhost