spring:
  application:
    name: api-gateway
    
server:
  port: 8079
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8032/eureka/
  instance:
    hostname: localhost
    
    
zuul:
  prefix: /api
  routes:
    task-service:
      path: /task-service/**
      url: http://localhost:8082/task-service
    user-service:
      path: /user-service/**
      url: http://localhost:8080/user-service